 version: '3.8'
 services:
   reno:
     build: .
     ports:
       - "8501:8501"
     volumes:
       - ./:/app
     environment:
       - STREAMLIT_SERVER_ENABLECORS=false
     command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0